version: '1.0.{build}'

image: Visual Studio 2017 

configuration:
  - Release

platform:
  - x64

environment:
  QT5: C:\Qt\5.12\msvc2017_64 
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

install:
  - vcpkg list
  - vcpkg install
        alembic
        --triplet %PLATFORM%-windows
  - vcpkg list
 
before_build:
    - md build
    - cd build
    - cmake .. -G "Visual Studio 15 2017 Win64"
            -DCMAKE_BUILD_TYPE=%CONFIGURATION%
            -DCMAKE_PREFIX_PATH=%QT5% 
            -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake 

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\INSTALL.vcxproj
  verbosity: minimal

# comment the above and uncomment the following to just build the dependencies
# build_script:
#  - echo "Dependencies installed."
 
cache:
  c:\tools\vcpkg\installed\
 
